/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppNotifications: typeof import('./src/components/common/AppNotifications.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DashboardPage: typeof import('./src/components/pages/DashboardPage.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginPage: typeof import('./src/components/pages/LoginPage.vue')['default']
    Message: typeof import('primevue/message')['default']
    NotFoundPage: typeof import('./src/components/pages/NotFoundPage.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    Playground: typeof import('./src/components/pages/Playground.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    WelcomePage: typeof import('./src/components/pages/WelcomePage.vue')['default']
  }
}
